version = 1

[[annotations]]
path = [
    "**/*",
]
precedence = "override"
SPDX-FileCopyrightText = "The VALESC Group members and external contributors (https://valesc.digital/thanks)"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
    "meta/gitignore.d/**",
]
precedence = "override"
SPDX-FileCopyrightText = "The VALESC Group members and external contributors (https://valesc.digital/thanks)"
SPDX-License-Identifier = "CC0-1.0"