[package]
name = "tinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.11"
bitflags = "2.8.0"
rand = "0.9.0"
mockall = "0.13.1"
log = "0.4.26"
env_logger = { version = "0.11.6", features = ["color"] }

[lints]
workspace = true